[controller]
# paths should be in between single quotes
input_config_path = './confs/SuperMetroid.json'

[skin]
skins_path = '/home/example/Documents/squabbler-retrospy-nintendospy-skins/skins'
skin_name = "snes-super-famicom-squabbler"
skin_theme = "black"
