[package]
name = "snes_input_display"
version = "0.1.1"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tungstenite = "0.20"
bitvec = "1"
quick-xml = { version = "0.30", features = ["overlapped-lists", "serialize"] }
config = "0.13"
dirs = "5"
ggez = "0.9"
rusb2snes = "0.1"