[package]
name = "snes_input_display"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tungstenite = "0.20"
strum_macros = "0.25"
bitvec = "1"
quick-xml = { version = "0.30", features = ["overlapped-lists", "serialize"] }
image = "0.24"
imageinfo = "0.7"
config = "0.13"
dirs = "5"
rusb2snes = "0.1"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["image"]
