[package]
name = "snes_input_display"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tungstenite = "*"
strum_macros = "0.24"
bitvec = "1.0.1"
quick-xml = { version = "0.28.1", features = ["overlapped-lists", "serialize"] }
image = "0.24.6"
imageinfo = "0.7.7"
config = "0.13.3"
dirs = "5.0.0"
rusb2snes = "0.1.0"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]
