[package]
name = "snes_input_display"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
websocket = "0.26"
strum_macros = "0.24"
clearscreen = "2.0.0"
bitarray = "0.10.0"
bit-array = "0.4.4"
bitvec = "1.0.1"
quick-xml = { version = "0.28.1", features = ["overlapped-lists", "serialize"] }
image = "0.24.6"
imageinfo = "0.7.7"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]



