on: push
        
env:
    CARGO_TERM_COLOR: always
  
jobs:
    build:
      strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
          # toolchain: stable
      runs-on: ${{ matrix.os }}
      steps:
  
      - name: Checkout
        uses: actions/checkout@v4

      # - run: echo ${{ github.workspace }}
  
      - name: Get Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          profile: minimal

      - name: Install alsa
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev
  
      - name: Install udev
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev
  
      # - name: Run cargo check --all-targets w/ -D warnings
      #   run: cargo check --all-targets
      #   env:
      #     RUSTFLAGS: "-D warnings"
  
      - name: Run cargo build --release
        run: cargo build --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: snes-input-display-${{ github.ref_name }}-${{ runner.os }}
          path:  ${{ github.workspace }}/snes_input_display/snes_input_display/target/release/snes_input_display