on: push
        
env:
    CARGO_TERM_COLOR: always
  
jobs:
    build:
      strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
          # toolchain: stable
      runs-on: ${{ matrix.os }}
      steps:
  
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Get Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          profile: minimal

      - name: Install alsa
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev
  
      - name: Install udev
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev
  
      - name: Run cargo check --all-targets w/ -D warnings
        run: cargo check --all-targets
        env:
          RUSTFLAGS: "-D warnings"
  
      - name: Run cargo test w/ -D warnings
        run: cargo build --release
        
      - uses: actions/upload-artifact@v4
        with:
          name: snes-input-viewer-${{ github.ref_name }}-${{ runner.os }}
          path: /home/runner/work/snes_input_display/snes_input_display